-- =============================================================
-- DekaBank Interview Prep: Seed / Reference Data
-- Run AFTER 01_schema.sql
-- =============================================================
SET search_path TO deka;
SET client_encoding = 'UTF8'; -- IMPORTANT: prevents umlaut corruption (ü,ö,ä,ß)

-- -------------------------------------------------------------
-- SPARKASSEN (10 real-style German savings banks)
-- -------------------------------------------------------------
INSERT INTO sparkassen (sparkasse_code, sparkasse_name, region, city) VALUES
  ('SPK-MUC',  'Stadtsparkasse München',              'Bayern',              'München'),
  ('SPK-FFM',  'Sparkasse Frankfurt am Main',         'Hessen',              'Frankfurt'),
  ('SPK-BER',  'Berliner Sparkasse',                  'Berlin',              'Berlin'),
  ('SPK-HAM',  'Hamburger Sparkasse',                 'Hamburg',             'Hamburg'),
  ('SPK-DUS',  'Stadtsparkasse Düsseldorf',           'Nordrhein-Westfalen', 'Düsseldorf'),
  ('SPK-STU',  'Kreissparkasse Böblingen',            'Baden-Württemberg',   'Stuttgart'),
  ('SPK-NUE',  'Sparkasse Nürnberg',                  'Bayern',              'Nürnberg'),
  ('SPK-KOL',  'Sparkasse KölnBonn',                  'Nordrhein-Westfalen', 'Köln'),
  ('SPK-LEI',  'Sparkasse Leipzig',                   'Sachsen',             'Leipzig'),
  ('SPK-HAN',  'Sparkasse Hannover',                  'Niedersachsen',       'Hannover');

-- -------------------------------------------------------------
-- FUNDS (10 DekaBank-style investment funds)
-- -------------------------------------------------------------
INSERT INTO funds (isin, fund_name, fund_type, currency, ter, inception_date) VALUES
  ('DE0008474503', 'DekaFonds',                         'EQUITY',       'EUR', 0.0145, '1956-09-20'),
  ('DE0008474511', 'Deka-EuropaPotential TF',           'EQUITY',       'EUR', 0.0165, '1999-03-01'),
  ('LU0062624902', 'DekaLux-Deutschland TF A',          'EQUITY',       'EUR', 0.0140, '1997-10-01'),
  ('DE000DK2CFT0', 'Deka-BasisAnlage konservativ',      'MIXED',        'EUR', 0.0088, '2003-06-02'),
  ('DE000DK2CFU8', 'Deka-BasisAnlage ausgewogen',       'MIXED',        'EUR', 0.0105, '2003-06-02'),
  ('DE000DK2CFV6', 'Deka-BasisAnlage dynamisch',        'MIXED',        'EUR', 0.0125, '2003-06-02'),
  ('DE0009771980', 'Deka-EuroGarant 90',                'BOND',         'EUR', 0.0065, '2001-04-03'),
  ('DE000DK0LLA4', 'Deka-Nachhaltigkeit Aktien TF',     'EQUITY',       'EUR', 0.0170, '2019-08-01'),
  ('DE000DK0M9W3', 'DekaImmobilien Europa',             'REAL_ESTATE',  'EUR', 0.0095, '2002-01-14'),
  ('DE000DK2D8S9', 'Deka-Geldmarkt: Euro TF',           'MONEY_MARKET', 'EUR', 0.0025, '1999-07-01');

-- -------------------------------------------------------------
-- NOTE: Customers, depots, fund_nav, holdings, and transactions
-- are generated by python/generate_data.py
-- Run: python python/generate_data.py
-- Then load CSVs with the \copy commands in the README
-- -------------------------------------------------------------
